# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8305d1b23a5af29aae2a7a8dd16189328a74be60a73edd641c85cde8ad93077977328d8d2e7a1a0456624ffe4951b97a33dc557b70c810e92d059746cafee96

test:
  secret_key_base: 8de6d61be8328f6d9623388ac88beba8fdb42295ea314d6c6b4e34f77bf41d22614f4fda8f87ebe1de2da379d93596a14b842452666fbfa614d2e5005f6b351d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
